---
- hosts: all
  gather_facts: false
  tasks:
  - name: Unzip a package script
    win_unzip:
      src: C:\DUWF\PacotesQualidade\test\DealerNetRelatorio.gz
      dest: C:\DUWF\PacotesQualidade\test-archive
      creates: C:\DUWF\PacotesQualidade\test-archive