---
- hosts: all
  gather_facts: no
  tasks:
  - name: Search all updates
    win_updates:
      category_names:
      - CriticalUpdates
      - SecurityUpdates
      - UpdateRollups
      log_path: C:\Temp\ansible-windows-update.txt
      state: searched